motivational_quotes = [
    "Problems are not stop signs, they are guidelines.",
    "Be kind whenever possible. It is always possible.",
    "I attribute my success to this - I never gave or took any excuse.",
    "Set your goals high, and don't stop till you get there.",
    "The secret of getting ahead is getting started.",
    "If you fell down yesterday, stand up today.",
    "It does not matter how slowly you go as long as you do not stop.",
    "A good plan violently executed now is better than a perfect plan executed next week.",
    "When something is important enough, you do it even if the odds are not in your favor.",
    "If you can dream it, you can do it.",
    "What you do today can improve all your tomorrows.",
    "Our greatest weakness lies in giving up. The most certain way to succeed is always to  try just one more time.",
    "It always seems impossible until it's done.",
    "Quality is not an act, it is a habit.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "Either move or be moved.",
    "Start where you are. Use what you have. Do what you can.",
    "The most effective way to do it, is to do it.",
    "You just can't beat the person who never gives up.",
    "I am not afraid.. I was born to do this.",
    "Failure will never overtake me if my determination to succeed is strong enough.",
    "A creative man is motivated by the desire to achieve, not by the desire to beat others.",
    "Knowing is not enough; we must apply. Willing is not enough; we must do.",
    "Be miserable. Or motivate yourself. Whatever has to be done.",
    "Only I can change my life. No one can do it for me.",
    "The past cannot be changed. The future is yet in your power.",
    "One way to keep momentum going is to have constantly greater goals.",
    "Do your work with your whole heart, and you will succeed - there's so little competition.",
    "A goal is a dream with a deadline.",
    "Expect problems and eat them for breakfast.",
    "I can, therefore I am.",
    "You will never win if you never begin.",
    "The hardships I encountered in the past will help me succeed in the future.",
    "After a storm comes a calm.",
    "You have to make it happen.",
    "Big shots are only little shots who keep shooting.",
    "The more things you do, the more you can do.",
    "He conquers who endures.",
    "Step by step and the thing is done.",
    "When one must, one can.",
    "Go big or go home. What do you have to lose?",
    "I come to win.",
    "I thank all my failures for making me a success.",
]
