# Generated by Django 5.0.6 on 2024-05-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="date_written",
            field=models.DateTimeField(),
        ),
    ]
